### ISSUE TITLE
Status Light 

### ISSUE THREAD

**Issue by BenouGui** [openhomekit/homebridge-nhc2#5]
Hello, since the last update 3.1.0 the status of the lamps no longer goes up in homekit. If we turn on via homekit it's ok but if we turn on the lamp via the switch the status on homekit remains off.
Bien à vous

**Comment by samuel-verdonck** [comment]
There is an open pull request to fix this

**Comment by rubencallewaert** [comment]
Hello! Thanks for creating an issue, Should be fixed by https://github.com/openhomekit/homebridge-nhc2/pull/4 in v3.1.1
